#!/bin/bash

#Bash script that pings google's dns server to verify internet connectivity.
#Script logs the time of failed ping and calculates internet outage time based on
#next successful ping. 


#Modify myHost variable if you want to ping something other than Google DNS

myHost="8.8.8.8"
#Dead 0 is no, 1 is yes
ping_attempts=1
dead=0

while :
do
	count=$(ping -c $ping_attempts $myHost | awk -F, '/received/{print $2*1}')
	if [ $count -eq 0 ] && [ $dead -lt 3 ]; then
	    deadtime=$(date +%s)
	    let dead=dead+1
	fi

	if [ $count -eq 1 ] && [ $dead -eq 3 ]; then
		alivetime=$(date +%s)
		reported=$(curl icanhazip.com)
		diff=$(($alivetime-$deadtime))
		echo -e "Connection back online.\nThe outage lasted $(($diff / 60)) minutes and $(($diff % 60)) seconds.\nIP: $reported" | mailx -v -s "Outage Report" DESINATION
		dead=0
	fi


	sleep 5
done
